export const MATCH_REPOSITORY = Symbol('MATCH_REPOSITORY');
export const PLAYER_PROFILE_REPOSITORY = Symbol('PLAYER_PROFILE_REPOSITORY');
export const MATCH_RECORD_REPOSITORY = Symbol('MATCH_RECORD_REPOSITORY');
